#!/bin/bash

#Source vars:
root_dir=$(dirname "$(pwd)")
export root_dir
. "$root_dir/.env"
. "$root_dir/scripts/setup.core"
. "$root_dir/scripts/start.core"
. "$root_dir/scripts/status.core"
. "$root_dir/scripts/stop.core"

CLI_NAME="BTC Fee Tracker"
CLI_VERSION="0.1.1"

show_op_help.log() {
    cat <<EOF
echo "$CLI_NAME: $CLI_VERSION"
Usage: bft [OPTIONS] COMMAND [ARGUMENTS]

Commands:
--------------------------------------------------------
setup                 install service
start                 start service  
stop                  stop service

Options:
--------------------------------------------------------
-v, --version  view CLI version
-h, --help     view help

EOF
}
#
#
# Main CLI logic
#
#

if [ "$#" -eq 0 ]; then
    show_op_help.log
    exit 1
fi

case "$1" in
-h | --help)
    show_op_help.log
    exit 0
    ;;
-v | --version)
    echo "$CLI_NAME v$CLI_VERSION"
    exit 0
    ;;
setup)
    core.setup
    exit 0
    ;;
start)
    core.start
    exit 0
    ;;
status)
    core.status
    exit 0
    ;;
stop)
    core.stop
    exit 0
    ;;
# ... [Any other cases you might have previously]
*)
    echo "Error: Unknown command: $1"
    show_op_help.log
    exit 1
    ;;
esac
